# -*- coding: utf-8 -*-
"""Project 105

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AKoLEesgoMXre2wScXhGAW0aqvf5Msm1
"""

from google.colab import files
data = files.upload()

import pandas as pd
import plotly.express as px
import statistics

df = pd.read_csv("Project 105.csv")
fig = px.scatter(df, x = "Team1", y = "Team2")
fig.show()

"""There is some issue with the file"""